# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site information
title: The Joey D Internals
email: jdwonczyk.corp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Discussing all things Sustainability, Health & Technology
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
# url: "https://dfederm.com"
# url: "http://dwonczykj.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# https://dfederm.com/creating-a-blog-using-github-pages/
# Site settings
twitter_username: joey_m_d
github_username:  Dwonczykj
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

disqus:
  shortname: dwonczykj-github-io

# disqus_url: dwonczykj-github-io.disqus.com

google_analytics: 225673403
# google_ads: ca-pub-7807152857287265

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# sass:
#   sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
